name: Build Femboy Linux ISO
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Build Tools
        run: |
          sudo apt update
          sudo apt install live-build -y
      - name: Cook the ISO
        run: |
          mkdir build && cd build
          lb config --debian-installer live --archive-areas "main contrib non-free"
          # Aqui os comandos que a gente treinou no Termux entram automaticamente
          echo "femboy-linux" > config/includes.chroot/etc/hostname
          sudo lb build
      - name: Upload ISO
        uses: actions/upload-artifact@v3
        with:
          name: Femboy-Linux-ISO
          path: build/*.iso
          
