name: Build Femboy Linux ISO
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Build Tools
        run: |
          sudo apt update
          sudo apt install live-build -y
      - name: Cook the ISO
        run: |
          mkdir build && cd build
          sudo lb config --debian-installer live --archive-areas "main contrib non-free"
          sudo lb build
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: Femboy-Linux-ISO
          path: build/*.iso

